name: Stream2
on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Install tools
        run: |
          sudo apt-get install -y ffmpeg
          pip install gdown

      - name: Download files
        run: |
          gdown 1z-dOnuBqFZY0CRSdo4SPtue0ACRRcwaC -O video.mp4
          gdown 1krr-Qk_El6pk3ZdFjzJXfpYZ2ijdxpzL -O audio.mp3

      - name: Start Stream
        run: |
          ffmpeg -stream_loop -1 -re -i video.mp4 \
          -stream_loop -1 -re -i audio.mp3 \
          -map 0:v -map 1:a -c:v copy -c:a aac -b:a 128k \
          -f flv rtmp://live.restream.io/live/${{ secrets.STREAM_KEY }}
