name: Prepare
on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:

      - name: Install tools
        run: |
          sudo apt-get install -y ffmpeg
          pip install gdown

      - name: Download video
        run: gdown 1Cr8G_0gD4LgabKztsIJOp0ddlUYqXNK2 -O video.mp4

      - name: Convert video to H264
        run: |
          ffmpeg -i video.mp4 -c:v libx264 -preset veryfast -crf 23 -an video_h264.mp4

      - name: Download audio files
        run: |
          gdown 1TOMytDgeII2GDspmHZ-kbAis-juK2iqp -O a1.tmp && ffmpeg -i a1.tmp audio1.mp3 -y
          gdown 10Z5lBwM4zr3JsEcd_2KY7vB0qOJRjNjo -O a2.tmp && ffmpeg -i a2.tmp audio2.mp3 -y
          gdown 17nqAmBYExskUmySAzB51NAxic5XJRuLj -O a3.tmp && ffmpeg -i a3.tmp audio3.mp3 -y
          gdown 1IbkCM0FYurEzKBBWB-GYyMVA-Js2zbQM -O a4.tmp && ffmpeg -i a4.tmp audio4.mp3 -y
          gdown 1XkDh8_5rNV8CZtgMdR-82lcWAVPbxwcL -O a5.tmp && ffmpeg -i a5.tmp audio5.mp3 -y
          gdown 1BVe4zBJBYdkSgCpyWG7Xi4iMbbyVX5Eq -O a6.tmp && ffmpeg -i a6.tmp audio6.mp3 -y
          gdown 1F2LQM5tQjJkyA2u_kTzKf3uTm7gS8F_S -O a7.tmp && ffmpeg -i a7.tmp audio7.mp3 -y
          gdown 1qkBtQe6NHlKoThu4W1jIT4Nc7HoEzOef -O a8.tmp && ffmpeg -i a8.tmp audio8.mp3 -y
          gdown 1TXbWo89v0e8RMkwuuwkilB24LdCc0Xkn -O a9.tmp && ffmpeg -i a9.tmp audio9.mp3 -y
          gdown 1pcFXubIlecpZCyWEbVZ-ZXeJbBvemnik -O a10.tmp && ffmpeg -i a10.tmp audio10.mp3 -y
          gdown 1lI1QjxrDFraxniv2Dzvs3O9s0w_kRuqx -O a11.tmp && ffmpeg -i a11.tmp audio11.mp3 -y

      - name: Create playlist and merge
        run: |
          ls audio*.mp3 | shuf > playlist.txt
          while IFS= read -r file; do
            echo "file '$file'"
          done < playlist.txt > concat.txt
          ffmpeg -f concat -safe 0 -i concat.txt -c copy merged_audio.mp3

      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: |
            video_h264.mp4
            merged_audio.mp3
          key: media-files-v2
