name: Stream-01
on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 359
    steps:

      - name: Install tools
        run: |
          sudo apt-get install -y ffmpeg
          pip install gdown

      - name: Download video
        run: gdown 1AOyK6tYphq81bt9LC5okcxA0JqNJdR-C -O video.mp4

      - name: Download audio files
        run: |
          gdown 1TOMytDgeII2GDspmHZ-kbAis-juK2iqp -O a1.tmp && ffmpeg -i a1.tmp audio1.mp3 -y
          gdown 10Z5lBwM4zr3JsEcd_2KY7vB0qOJRjNjo -O a2.tmp && ffmpeg -i a2.tmp audio2.mp3 -y

      - name: Create playlist and merge
        run: |
          ls audio*.mp3 | shuf > playlist.txt
          while IFS= read -r file; do
            echo "file '$file'"
          done < playlist.txt > concat.txt
          ffmpeg -f concat -safe 0 -i concat.txt -c copy merged_audio.mp3

      - name: Start Stream
        run: |
          ffmpeg -stream_loop -1 -re -i video.mp4 \
          -stream_loop -1 -re -i merged_audio.mp3 \
          -map 0:v -map 1:a -c:v copy -c:a aac -b:a 128k \
          -f flv rtmp://live.restream.io/live/${{ secrets.STREAM_KEY }}
